### ISSUE TITLE
`hyper run` local container

### ISSUE THREAD

**Issue by MayasHaddad** [hyperhq/hypercli#247]
I am new to `hyper.sh`

I built a container using docker, copied to it a `node.js` app.

Unfortunately, I fail to find the relevant command to deploy my local container.

Is there a way I can achieve that?

**Comment by gnawux** [comment]
hi @MayasHaddad , 

In order to run containers on hyper.sh, you need a hyper.sh account firstly. Then you may use `hyper pull` to get image from a registry and `hyper run` to run a container.

If you have already had a local one, the easiest way should be -- commit it as an image and push to hub with docker, and pull/run with hyper.
